# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: app-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports: 
      - "5435:5432"
    volumes:
      - ./tmp:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server:
    build: server/
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    command: node server.js
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
